// A short, kid-friendly fun fact for each animal friend, keyed by name.
export const FACTS = {
  'Bun-Bun': 'A rabbit’s teeth never stop growing!',
  Cluck: 'Chickens can remember more than 100 faces!',
  Pip: 'Dogs can smell a thousand times better than people!',
  Hoppy: 'Frogs drink water through their skin!',
  Shelly: 'A turtle’s shell is part of its body!',
  Bubbles: 'Many fish sleep with their eyes open!',
  Ollie: 'An octopus has three hearts!',
  Waddle: 'Penguins can’t fly, but they are amazing swimmers!',
  Rusty: 'Foxes can leap high in the air to pounce!',
  Coco: 'Monkeys use their tails to hold on to branches!',
  Tembo: 'Elephants say hello with their trunks!',
  Sparkle: 'Unicorns are magical and love rainbows!',
  Buzz: 'Bees do a little dance to share where flowers are!',
  Clover: 'Horses can sleep standing up!',
  Hoot: 'Owls can turn their heads almost all the way around!',
  Splash: 'Dolphins call each other by name!',
  Bamboo: 'Pandas can eat bamboo for many hours a day!',
  Stretch: 'A giraffe’s tongue is as long as your arm!',
  Gumnut: 'Koalas sleep up to 20 hours a day!',
  Rosie: 'Flamingos turn pink from the food they eat!',
  Rio: 'Parrots can learn to say lots of words!',
  Mossy: 'Sloths are so slow that tiny plants grow on them!',
  Otto: 'Otters hold hands while they sleep so they don’t drift apart!',
  Prickle: 'Hedgehogs roll into a spiky ball when they feel scared!',
  Nibbles: 'Hamsters stuff food in their cheeks to carry it home!',
  Bandit: 'Raccoons like to wash their food before they eat!',
  Nutty: 'Squirrels hide thousands of nuts for the winter!',
  Echo: 'Bats can “see” in the dark using sound!',
  Flutter: 'Butterflies taste with their feet!',
  Dot: 'Ladybugs can have different numbers of spots!',
  Gary: 'Snails carry their homes on their backs!',
  Gecko: 'Geckos can walk straight up walls!',
}
